context:
  name: blender-mathutils
  version: "5.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mathutils/mathutils-${{ version }}.tar.gz
  sha256: b171af9d6b54a12138c9dead4f5930a3faaf92387cc5ffaa82f18fbee1554168
  patches:
    - patches/py313_fix.patch

build:
  skip:
    - match(python, "<3.10")
  script: python -m pip install . -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - mathutils
      pip_check: true

about:
  homepage: https://gitlab.com/ideasman42/blender-mathutils
  summary: 'A general math utilities library providing Matrix, Vector, Quaternion, Euler and Color classes, written in C for speed.'
  description: |
    This module originated from Blender (the opens-source 3d package),
    where it has been used for some years in production as a utility module for use in areas including animation,
    games and mesh manipulation.

    This differs from numpy in that it is computer graphics focused,
    combining Matrix and Vector types with rotation classes which is very useful
    for use with animation or anywhere Euler and Quaternion values are used frequently.

    This project is mainly a build system around the actively maintained mathutils code in
    Blender to allow non Blender related projects to make use of it.

    A link to the Blender repository is used so the source never gets out of sync.
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  repository: https://gitlab.com/ideasman42/blender-mathutils

extra:
  recipe-maintainers:
    - Krande
